import { StyleSheet } from 'react-native';

const notesManagerStyles = StyleSheet.create({
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    notesModal: {
        width: '90%',
        minHeight: '70%',
        backgroundColor: '#fff',
        borderRadius: 10,
        position: 'relative',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor:'#5BA191',
        paddingVertical:14,
        paddingHorizontal:25,
    },
    modalTitle: {
        fontSize: 20,
        fontFamily: 'Manrope-Regular',
        color: '#FFF',

    },
    notesList: {
        flex: 1,
        marginVertical: 10,
        paddingHorizontal:20,
    },
    noteItem: {
        fontSize: 18,
        marginVertical: 5,
        padding: 10,
        backgroundColor: '#E8F6F4',
        borderRadius: 8,
        flexDirection:'row',
    },
    noteItemTitle:{
        fontSize: 18,
        color:'#1E1E1E',
        fontFamily: 'Manrope-Regular',
        marginLeft:10,
    },
    addNoteButton: {
        backgroundColor: '#5BA191',
        padding: 12,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 10,
        margin:20,
    },
    addNoteButtonText: {
        color: '#FFF',
        fontSize: 18,
        fontFamily: 'Manrope-Regular',
    },
    addNoteModal: {
        width: '90%',
        minHeight: '70%',
        backgroundColor: '#fff',
        borderRadius: 10,
        position: 'relative',
    },
    addNotesForm:{
        flex: 1,
        marginVertical: 10,
        paddingHorizontal:20,
        justifyContent:'center',
    },
    addNotesFormLabel:{
        fontFamily: 'Manrope-Regular',
        backgroundColor: '#5BA191',
        color:'#FFF',
        textAlign:'center',
        borderRadius:30,
        marginBottom:5,
        paddingHorizontal:15,
        paddingVertical:8,

    },
    input: {
        width: '100%',
        height: 40,
        borderColor: '#5BA191',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 10,
        marginBottom: 10,
        fontFamily: 'Manrope-Regular',
    },
    textArea: {
        height: 100,
        textAlignVertical: 'top',
        borderColor: '#5BA191',
        borderWidth: 1,
        borderRadius: 8,
        fontFamily: 'Manrope-Regular',
    },
    notedetailetextArea: {
        height: 500,
        flex: 1,
        paddingVertical: 10,
        textAlignVertical: 'top',
        borderColor: '#5BA191',
        borderWidth: 1,
        borderRadius: 8,
    },
    modalButtons: {
        marginTop: 20,
    },
    saveButton: {
        backgroundColor: '#5BA191',
        padding: 10,
        borderRadius: 8,
        alignItems: 'center',
    },
    saveButtonText: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'Manrope-Regular',
    },
    cancelButton: {
        backgroundColor: '#5BA191',
        padding: 10,
        borderRadius: 8,
        alignItems: 'center',
        marginTop:10,
    },
    cancelButtonText: {
        color: '#FFF',
        fontSize: 16,
        fontFamily: 'Manrope-Regular',
    },
    editButton: {
        backgroundColor: '#5BA191',
        padding: 10,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 10,
    },
    editButtonText: {
        color: '#FFF',
        fontSize: 16,
        fontFamily: 'Manrope-Regular',
    },
    saveChangesButton: {
        backgroundColor: '#5BA191',
        padding: 10,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 10,
    },
    saveChangesText: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'Manrope-Regular',
    },
    noteContentInput: {
        width: '100%',
        height: 150,
        borderColor: '#5BA191',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 10,
        textAlignVertical: 'top',
        marginTop: 10,
    },
    closeIcon: {
        color: '#FFF',
    },
    textAreaScrollable: {
        flex: 1,
        paddingVertical: 10,
    },
    textInput: {
        flex: 1,
        height: 'auto',
        padding: 10,
        textAlignVertical: 'top',
    },
    deleteButton: {
        backgroundColor: '#5BA191',
        padding: 10,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 10,
    },
    deleteButtonText: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'Manrope-Regular',
    },
});

export default notesManagerStyles;
